site_name: BirdDog Documentation
site_url: https://docs.getbirddog.ai

theme:
  name: material
  palette:
    # Light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Light Mode
    # Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
  logo: assets/scout_head_big.png
  favicon: assets/scout_head_big.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.prefetch
    # removed: toc.integrate
    - navigation.expand
    - navigation.prune

extra_css:
  - assets/brand.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Getting Started: quick_start_guide.md
  - Explaination By Page:
      - Home Page: home_page.md
      - Farsight Page: farsight_page.md
      - Signals Page: signals_page.md
      - Account Manager Page: account_manager.md
      - Team Page: team_page.md
  - Improving Signals:
      - Signals Guide: signals_guide.md
      - Improving Accuracy: signal_context.md 
  - Integrations:
      - Google Calendar: gcal.md
      - Hubspot: hubspot.md
      - Salesforce: salesforce.md
  - Resources:
      - FAQ: frequently_asked_questions.md
      - Email Templates: email_templates.md
  
