site_name: BirdDog Tutorials
site_url: https://docs.getbirddog.ai

theme:
  name: material
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom   # Use custom to link to our CSS variables
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Light Mode
    # Dark Mode (Slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom   # Use custom to link to our CSS variables
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
  logo: assets/scout_head_big.png
  favicon: assets/scout_head_big.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.prefetch
    - navigation.expand
    - navigation.prune

extra_css:
  - assets/brand.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Getting Started: quickstart.md
  - Accounts:
      - How to add accounts: adding_account.md
      - How to get recommendations: account_rec_setup.md
      - How to Remove Accounts: remove_accounts.md
      - How to archive accounts: archiving_accounts.md
  - Plays:
      - How to create Plays: create_plays.md
      - How to delete a Play: delete_play.md
      - How to edit play: edit_play.md
  - Account Recommendations:
      - How to setup: account_rec_setup.md
      - How to adjust/improve Recommendations: adjust_recommendations.md
      - How to give feedback on recommendations: rec_feedback.md
  - Integrations:
      - Hubspot: hubspot.md
      - Slack: slack.md
      - Google Calendar: gcal.md
      - Salesforce: salesforce.md
  - User Management:
      - Adding Users: adding_user.md
      - Removing Users: removing_user.md
  - Signals:
      - How to setup new signal: signal_setup.md
      - How to improve: improve_signal.md
      - How to delete signals: delete_signal.md
      - How to mute signals: mute_signal.md
      - Signals Library and Best Practices: signals_guide.md
  - Frequently Asked Questions: frequently_asked_questions.md
